### ISSUE TITLE
building the debian package

### ISSUE THREAD

**Issue by spacedream** [loki-project/lokinet-builder#5]
$ debuild -b -us -uc
...
[ 41%] Building C object CMakeFiles/lokinet-static.dir/crypto/libntrup/src/ref/r3_recip.c.o
[ 42%] Building C object CMakeFiles/lokinet-static.dir/crypto/libntrup/src/ref/keypair.c.o
[ 42%] Building C object CMakeFiles/lokinet-static.dir/crypto/libntrup/src/ref/rq_rounded.c.o
[ 43%] Building C object CMakeFiles/lokinet-static.dir/crypto/libntrup/src/ref/enc.c.o
[ 44%] Building C object CMakeFiles/lokinet-static.dir/crypto/libntrup/src/ref/int32_sort.c.o
[ 44%] Building C object CMakeFiles/lokinet-static.dir/crypto/libntrup/src/ref/rq.c.o
[ 45%] Building CXX object CMakeFiles/lokinet-static.dir/crypto/libntrup/src/ntru.cpp.o
/home/sd/tmp/lokinet-builder/deps/llarp/crypto/libntrup/src/ntru.cpp: In function ‘bool supports_avx2()’:
/home/sd/tmp/lokinet-builder/deps/llarp/crypto/libntrup/src/ntru.cpp:27:43: error: ‘printf’ was not declared in this scope
   printf("AVX2 disabled on compile time\n");
                                           ^
CMakeFiles/lokinet-static.dir/build.make:830: recipe for target 'CMakeFiles/lokinet-static.dir/crypto/libntrup/src/ntru.cpp.o' failed
make[5]: *** [CMakeFiles/lokinet-static.dir/crypto/libntrup/src/ntru.cpp.o] Error 1
make[5]: Leaving directory '/home/sd/tmp/lokinet-builder/build'
CMakeFiles/Makefile2:146: recipe for target 'CMakeFiles/lokinet-static.dir/all' failed
make[4]: *** [CMakeFiles/lokinet-static.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
[ 45%] Linking CXX static library libgtest.a
make[5]: Leaving directory '/home/sd/tmp/lokinet-builder/build'
[ 45%] Built target gtest
make[4]: Leaving directory '/home/sd/tmp/lokinet-builder/build'
Makefile:127: recipe for target 'all' failed
make[3]: *** [all] Error 2
make[3]: Leaving directory '/home/sd/tmp/lokinet-builder/build'
Makefile:116: recipe for target 'debian' failed
make[2]: *** [debian] Error 2
make[2]: Leaving directory '/home/sd/tmp/lokinet-builder'
debian/rules:21: recipe for target 'override_dh_auto_build' failed
make[1]: *** [override_dh_auto_build] Error 2
make[1]: Leaving directory '/home/sd/tmp/lokinet-builder'
debian/rules:5: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
debuild: fatal error at line 1116:
dpkg-buildpackage -rfakeroot -us -uc -b failed
$

**Comment by majestrate** [comment]
what platform are build building on?

**Comment by spacedream** [comment]
x86_64

16. Aug 2018 13:15 by notifications@github.com <mailto:notifications@github.com>:

**Comment by spacedream** [comment]
fresh installed Devuan, 
by command **make**
few warnings was like:

> libtool: warning: '-version-info/-version-number' is ignored for convenience libraries

everything assembled well.

BUT, by command 
**debuild -b -us -uc**
...
[ 96%] Linking CXX executable lokinet
[ 96%] Building CXX object CMakeFiles/testAll.dir/test/base32_unittest.cpp.o
[ 97%] Building CXX object CMakeFiles/testAll.dir/test/dht_unittest.cpp.o
[ 98%] Building CXX object CMakeFiles/testAll.dir/test/encrypted_frame_unittest.cpp.o
[ 98%] Building CXX object CMakeFiles/testAll.dir/test/hiddenservice_unittest.cpp.o
[ 99%] Building CXX object CMakeFiles/testAll.dir/test/pq_unittest.cpp.o
[100%] Linking CXX executable testAll
make[5]: Leaving directory '/home/sd/tmp/lokinet-builder/build'
[100%] Built target lokinet
make[5]: Leaving directory '/home/sd/tmp/lokinet-builder/build'
[100%] Built target testAll
make[4]: Leaving directory '/home/sd/tmp/lokinet-builder/build'
make[3]: Leaving directory '/home/sd/tmp/lokinet-builder/build'
cp /home/sd/tmp/lokinet-builder/build/lokinet /home/sd/tmp/lokinet-builder/lokinet
make[2]: Leaving directory '/home/sd/tmp/lokinet-builder'
make[1]: Leaving directory '/home/sd/tmp/lokinet-builder'
   dh_auto_test
   dh_testroot
   dh_prep
   dh_auto_install
   dh_install
   dh_installdocs
   dh_installchangelogs
   dh_installman
   dh_perl
   dh_link
   dh_strip_nondeterminism
   dh_compress
   dh_fixperms
   dh_strip
   dh_makeshlibs
   dh_shlibdeps
   dh_installdeb
   dh_gencontrol
   dh_md5sums
   dh_builddeb
dpkg-deb: building package 'lokinet-dbgsym' in '../lokinet-dbgsym_0.1.0_amd64.deb'.
dpkg-deb: building package 'lokinet' in '../lokinet_0.1.0_amd64.deb'.
 dpkg-genbuildinfo --build=binary
 dpkg-genchanges --build=binary >../lokinet_0.1.0_amd64.changes
dpkg-genchanges: info: binary-only upload (no source code included)
 dpkg-source --after-build lokinet-builder
dpkg-buildpackage: info: binary-only upload (no source included)
Now running lintian...
Could not find a profile matching "{VENDOR}/main" for vendor devuan at /usr/share/lintian/commands/lintian line 1561.
Finished running lintian.
$:~/tmp/lokinet-builder$ 

maybe i missing something? i just did followed your instructions how to build it.
thanks!
ps: sorry for the delay.

**Comment by spacedream** [comment]
after run the binary:

./lokinet
[NFO] unnamed (617) 1536307269609 llarp/context.cpp:54	config [daemon.ini] loaded
[NFO] unnamed (617) 1536307269626 llarp/context.cpp:146	llarpd-0.1.0-1e233fe traffic correlation nation
[NFO] unnamed (617) 1536307269626 llarp/context.cpp:147	starting up
[NFO] unnamed (617) 1536307269710 llarp/context.cpp:115	nodedb_dir loaded 0 RCs from [./tmp-nodes]
[NFO] unnamed (617) 1536307269724 llarp/handlers/tun.cpp:81	set ifaddr to 10.10.0.1 with netmask 24
[NFO] unnamed (617) 1536307269724 llarp/handlers/tun.cpp:99	map k89rfz5to3ige3f9yymy7inm63pitehmf4sumqgnfdcew9ihtomy.loki to 10.10.0.2
[NFO] unnamed (617) 1536307269888 llarp/service/endpoint.cpp:52	isolating network to namespace lokinet
[NFO] unnamed (617) 1536307269888 llarp/handlers/tun.cpp:123	waiting for tun interface...
[ERR] unnamed (872) 1536307269891 llarp/linux/netns.cpp:265	Failed to open network namespace 'lokinet': No such file or directory
[ERR] unnamed (872) 1536307269891 llarp/threadpool.cpp:122	isolation failed: No such file or directory
[ERR] unnamed (617) 1536307269891 llarp/service/context.cpp:103	failed to start hidden service endpoint test
[WRN] unnamed (617) 1536307269892 llarp/router.cpp:1255	failed to load hidden service config for test
[NFO] unnamed (617) 1536307269892 llarp/router.cpp:842	outbound link initialized
[NFO] unnamed (617) 1536307269892 llarp/iwp/server.cpp:297	new transport key generated
[NFO] unnamed (617) 1536307269892 llarp/router.cpp:848	outbound link ready
[NFO] unnamed (617) 1536307269892 llarp/router.cpp:1140	generating new encryption key
[NFO] unnamed (617) 1536307269892 llarp/router.cpp:1112	generating new identity key
[NFO] unnamed (617) 1536307269893 llarp/router.cpp:684	You have 0 inbound links
[NFO] unnamed (617) 1536307269893 llarp/router.cpp:750	Your Encryption pubkey 15b75ac564db7199bf926513145943791fc0fef33f61ed3b1626c92f3e90be6c
[NFO] unnamed (617) 1536307269893 llarp/router.cpp:755	Your Identity pubkey ed1d2d693e8ee1e4827990fbf9693f106060d5d90a36e986549d76287e1b018b
[NFO] unnamed (617) 1536307269893 llarp/router.cpp:257	our RC saved to self.signed
[NFO] unnamed (617) 1536307269893 llarp/router.cpp:800	starting dht context as ed1d2d693e8ee1e4827990fbf9693f106060d5d90a36e986549d76287e1b018b
[NFO] unnamed (617) 1536307269893 llarp/context.cpp:203	running mainloop
[NFO] unnamed (617) 1536307270895 llarp/router.cpp:467	We need more than 3 service nodes to build paths but we have 0
[NFO] unnamed (617) 1536307271897 llarp/router.cpp:467	We need more than 3 service nodes to build paths but we have 0
[NFO] unnamed (617) 1536307272899 llarp/router.cpp:467	We need more than 3 service nodes to build paths but we have 0
[NFO] unnamed (617) 1536307273399 llarp/router.cpp:822	connecting to node i2procks
[NFO] unnamed (617) 1536307273559 llarp/iwp/session.cpp:507	send intro to 162.243.164.223:1090
[NFO] unnamed (617) 1536307273872 llarp/iwp/session.cpp:615	session gen start
[NFO] unnamed (617) 1536307273972 llarp/router.cpp:467	We need more than 3 service nodes to build paths but we have 1
[NFO] unnamed (617) 1536307274073 llarp/iwp/session.cpp:507	send intro to 162.243.164.223:1090
[NFO] unnamed (617) 1536307274271 llarp/iwp/session.cpp:615	session gen start
[NFO] unnamed (617) 1536307274727 llarp/iwp/session.cpp:136	Session to e0d5fa14e79accd1132cf140d40f0fe34c98aa3e6ad2cfb3315b63c7992c85a1 established
[NFO] unnamed (617) 1536307275046 llarp/router.cpp:467	We need more than 3 service nodes to build paths but we have 1
[NFO] unnamed (617) 1536307276048 llarp/router.cpp:467	We need more than 3 service nodes to build paths but we have 1
[NFO] unnamed (617) 1536307277050 llarp/router.cpp:467	We need more than 3 service nodes to build paths but we have 1
[NFO] unnamed (617) 1536307278099 llarp/router.cpp:467	We need more than 3 service nodes to build paths but we have 1
[NFO] unnamed (617) 1536307279101 llarp/router.cpp:467	We need more than 3 service nodes to build paths but we have 1
[NFO] unnamed (617) 1536307280132 llarp/router.cpp:467	We need more than 3 service nodes to build paths but we have 1
[NFO] unnamed (617) 1536307281133 llarp/router.cpp:467	We need more than 3 service nodes to build paths but we have 1
[NFO] unnamed (617) 1536307282135 llarp/router.cpp:467	We need more than 3 service nodes to build paths but we have 1
[NFO] unnamed (617) 1536307283188 llarp/router.cpp:467	We need more than 3 service nodes to build paths but we have 1
[NFO] unnamed (617) 1536307284190 llarp/router.cpp:467	We need more than 3 service nodes to build paths but we have 1
[NFO] unnamed (617) 1536307285254 llarp/router.cpp:467	We need more than 3 service nodes to build paths but we have 1
[NFO] unnamed (617) 1536307286256 llarp/router.cpp:467	We need more than 3 service nodes to build paths but we have 1
[NFO] unnamed (617) 1536307287258 llarp/router.cpp:467	We need more than 3 service nodes to build paths but we have 1
[NFO] unnamed (617) 1536307288342 llarp/router.cpp:467	We need more than 3 service nodes to build paths but we have 1
[NFO] unnamed (617) 1536307289344 llarp/router.cpp:467	We need more than 3 service nodes to build paths but we have 1
[NFO] unnamed (617) 1536307290350 llarp/router.cpp:467	We need more than 3 service nodes to build paths but we have 1
[NFO] unnamed (617) 1536307291352 llarp/router.cpp:467	We need more than 3 service nodes to build paths but we have 1
[NFO] unnamed (617) 1536307292354 llarp/router.cpp:467	We need more than 3 service nodes to build paths but we have 1
[NFO] unnamed (617) 1536307293374 llarp/router.cpp:467	We need more than 3 service nodes to build paths but we have 1
[NFO] unnamed (617) 1536307294376 llarp/router.cpp:467	We need more than 3 service nodes to build paths but we have 1
[NFO] unnamed (617) 1536307295423 llarp/router.cpp:467	We need more than 3 service nodes to build paths but we have 1
[NFO] unnamed (617) 1536307296425 llarp/router.cpp:467	We need more than 3 service nodes to build paths but we have 1
[NFO] unnamed (617) 1536307297426 llarp/router.cpp:467	We need more than 3 service nodes to build paths but we have 1
[NFO] unnamed (617) 1536307298517 llarp/router.cpp:467	We need more than 3 service nodes to build paths but we have 1
[NFO] unnamed (617) 1536307299519 llarp/router.cpp:467	We need more than 3 service nodes to build paths but we have 1
[NFO] unnamed (617) 1536307300601 llarp/router.cpp:467	We need more than 3 service nodes to build paths but we have 1
[NFO] unnamed (617) 1536307301604 llarp/router.cpp:467	We need more than 3 service nodes to build paths but we have 1
[NFO] unnamed (617) 1536307302606 llarp/router.cpp:467	We need more than 3 service nodes to build paths but we have 1
[NFO] unnamed (617) 1536307303694 llarp/router.cpp:467	We need more than 3 service nodes to build paths but we have 1
[NFO] unnamed (617) 1536307304696 llarp/router.cpp:467	We need more than 3 service nodes to build paths but we have 1
[NFO] unnamed (617) 1536307305767 llarp/router.cpp:467	We need more than 3 service nodes to build paths but we have 1
...
and its loop forever.

**Comment by majestrate** [comment]
yup that is the expected result as there is not a network to use as of right this moment.

that will change shortly, i have just pushed a redo of the inter node communication and
added dht exploration. This means that nodes should autodiscover the network given 1 good
peer. That is after everyone updates their though since this is the last change in the 
protocol that is backwards incompat without checks (probably).

~ Jeff

**Comment by majestrate** [comment]
debian package is updated now and the next release should be a LOT better.

**Comment by spacedream** [comment]
i use devuan, no systemd. its still failed for me. anyway, i understand now its not your fault, systemd just f*ck everything up already and from now and on will be only more worst...

**Comment by majestrate** [comment]
I have plans for other init scripts just no time to get them done at the moment.

Specifically openrc for freebsd and gentoo.

As of right now because systemd is the default in debian/ubuntu i use that for the packaging
as it will reach the most machines.

you can run it without systemd just fine using the manaul way of setting up:

$ lokinet -g && lokinet-bootstrap

then run to run in foreground:

$ lokinet

alternative packaging is a great way to get involved in the project.

i don't hard depend on systemd at the moment and probably never will unless there is a very
compelling reason to do so, such reasons to do so i suspect will never materialize.
